default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: <%= ENV['APPNAME_DATABASE_USER'] %>
  password: <%= ENV['APPNAME_DATABASE_PASSWORD'] %>
  host: localhost
  database: <%= ENV['DATABASE_NAME'] %>

test:
  <<: *default
  username: <%= ENV['APPNAME_DATABASE_USER'] %>
  password: <%= ENV['APPNAME_DATABASE_PASSWORD'] %>
  host: localhost
  database: talent_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: talent_production
  prepared_statements: false
  advisory_locks: false
